version: '3.9'
services:
    postgres:
        image: postgres:14-alpine
        ports:
            - "5433:5432"
        volumes:
            - "./data:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=kalman
            - POSTGRES_DB=auth
        restart: always